### ISSUE TITLE
Why is boto/boto3 excluded from package_lambda_code?

### ISSUE THREAD

**Issue by codesplicer** [ImmobilienScout24/pybuilder_aws_lambda_plugin#18]
I'm trying to package a pybuilder project for lambda and saw the following in the codebase: https://github.com/ImmobilienScout24/pybuilder_aws_plugin/blob/master/src/main/python/pybuilder_aws_plugin/lambda_tasks.py#L85

Is there a specific reason why boto/boto3 are being excluded from the lambda dependencies?

**Comment by esc** [comment]
Because boto/boto3 are installed already by default on the AWS Lambda execution environment. This means we don't need to include it in the lambda-zip.

On 16 May 2016 12:27:16 CEST, Vik Bhatti notifications@github.com wrote:

> I'm trying to package a pybuilder project for lambda and saw the
> following in the codebase:
> https://github.com/ImmobilienScout24/pybuilder_aws_plugin/blob/master/src/main/python/pybuilder_aws_plugin/lambda_tasks.py#L85
> 
> Is there a specific reason why boto/boto3 are being excluded from the
> lambda dependencies?
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImmobilienScout24/pybuilder_aws_plugin/issues/18

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by codesplicer** [comment]
@esc Great! Have opened PR https://github.com/ImmobilienScout24/pybuilder_aws_plugin/pull/19 to ensure this is in the readme too
